
function interacaojava() {
    document.getElementById("javaContent").innerHTML = "<strong>Procurar evoluir na minha linguagem primária, apesar da dificuldade que é o Java eu gosto bastante da mesma!</strong>"
}
function interacaojs() {
    document.getElementById("jsContent").innerHTML = "<strong>Tenho um curso Enorme de JavaScript na Udemy para terminar e me especializar mais ainda, confesso que tive dificuldades no começo mas depois de um tempo vi que é uma otima linguagem!</strong>"
}
function interacaoNode(){
    document.getElementById("nodeContent").innerHTML = "<strong>Comecei recentemente por ter gostado do JavaScript, um amigo meu que trabalha com Node me indicou, estou gostando bastante da mesma e tenho interesse em evoluir!</strong>"
}
function interacaodocker() {
    document.getElementById("dockerContent").innerHTML = "<strong>Fiz um curso de Ninja DevOps com meu amigo também pela Udemy, aprendi o basico do docker e me familiarizei com a interface!<strong>"
}